snowflake_poc:
  target: dev
  outputs:
    prod:
      type: snowflake
      account: "TTRYKFI-SCB24244" # e.g. xy12345.us-east-1
      user: "<your-username>"
      password: "<your-password>" # or use authenticator: externalbrowser
      role: poc_role
      database: analytics_db
      warehouse: wh_poc_xs
      schema: trips_staging # default; overridden per model in dbt_project.yml
      threads: 4
